### PR TITLE
Fix #4

### LINKED ISSUE #4: libname uses static path to home-path - breaks if user has another name
The current path to `qrcodegen(.so|.dll|.dylib)` is static and referencing to the path, where nimQR is located - the nimble path. But the nimble path is located in the `/home/user_name` area. If a program is compiled on Brians laptop, then when runned on Carlas laptop it'll fail, since it will be looking in `/home/Brian/...../include/qrcodegen.so` and that path does not exists.

https://github.com/ThomasTJdev/nim_qr/blob/54473dbdf8c8377e77088dc2442e9699c2fd799a/src/qr/qrcodegen.nim#L59-L69

### PR DESCRIPTION
**Pull request by juancarlospaco**
### This is what I know and I tested

- When you run the app is not Nim/Nimble that searchs for the `.so` is the operating system itself.
- You can not search for `.so` at run-time, it must be "hardcoded" at compile time, because is used as soon as the app runs.
- You can load from full path but it must be recompiled when used on another computer.
- You can not load from relative paths.
- You can copy the `.so` to `/temp/qrcodegen.so` and use `/temp/qrcodegen.so` as the path, but that will stop working after reboot.
- You can load from filename only, and the system should find the library automatically, this is the way it meant to be used I think.
- For installation of the `.so` you need privileges on all OS, sudo on Linux, Administrator on Windows, etc.
- This is not something with Nim, Rust and others have the same behaviors and rules.

Nim you have to install the DLL manually as seen here:

- https://nim-lang.org/download/dlls.zip

Nim stdlib uses just the filename only:
- https://github.com/nim-lang/Nim/blob/46ca19ff18ef3db72abf740da7795eb84306305e/lib/wrappers/postgres.nim#L21-L29
- https://github.com/nim-lang/Nim/blob/46ca19ff18ef3db72abf740da7795eb84306305e/lib/wrappers/mysql.nim#L15-L23
- https://github.com/nim-lang/Nim/blob/9995f50050298dc435a237b29dd0ff258ba25b9b/tests/deps/zip-0.2.1/zip/zzip.nim#L22-L27

---

### What I have done 

- I added a `try: ... except:` to try to copy the `.so`, it may work, it may fail.
- I added a `{.strdefine.}` so you can use something like `-d:libname=path/to/lib/qrcodegen.so`.
- Fix Deprecation errors.
- Added basic test on `when isMainModule:` block, can be changed to `runnableExamples:` block too.
- Improvements on the performance/logic of the module.
- Bump version, because of the changes.

Others:
- Added image file output to string or file, Pixmap format.

### CODE REVIEW

File: src/qr.nim [hunk 1]
```diff
@@ -113,38 +103,65 @@ proc qrSvgGenerate(qrcodeData: ptr uint8, svgSize: int32, border: cint, fgColor
...
 
       inc(x)
       svgY += svgYadd
 
     inc(y)
     svgX += svgYadd
 
-  return svgOpen & output & svgClose
+  # bgColor and fgColor is formatted at compile-time. Sizes and data is formatted at run-time.
+  result = static("""<?xml version="1.0" encoding="utf-8"?><svg width="$$1" height="$$1" viewBox="0 0 $$1 $$1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:ev="http://www.w3.org/2001/xml-events"><rect x="0" y="0" width="$$1" height="$$1" fill="$1"/><defs><rect id="p" width="$$2" height="$$2"/></defs><g fill="$2">$$3</g></svg>""" % [bgColor, fgColor]
```
Comment (ThomasTJdev) [inline src/qr.nim:115]: Multiple `$` inserted, e.g. `$$2`

File: src/qr.nim [hunk 2]
```diff
@@ -75,36 +74,27 @@ func qrRow*(data: string, eccLevel = Ecc_Medium, verMin: cint = VERSION_MIN, ver
...
       inc(x)
     inc(y)
-    container.add(output)
+    result.add output
     output = @[]
-  return container
 
 
-proc qrSvgGenerate(qrcodeData: ptr uint8, svgSize: int32, border: cint, fgColor = "#000000", bgColor = "#ffffff"): string =
+func qrSvgGenerate(qrcodeData: ptr uint8, svgSize: int32, border: cint, fgColor: static string = "#000000", bgColor: static string = "#ffffff"): string {.noinit.} =
```
Comment (ThomasTJdev) [inline src/qr.nim:81]: Is the `static string` just the type definition of `bgColor`?

`bgColor: static string = "#ffffff"`

File: src/qr/qrcodegen.nim [hunk 3]
```diff
@@ -54,19 +54,10 @@
 
 import os
 
+const libname* {.strdefine.} = currentSourcePath().parentDir / "qrcodegen." & (when defined(windows): "dll" elif defined(macosx): "dylib" else: "so") ## Dynamic Library
```
Comment (ThomasTJdev) [inline src/qr/qrcodegen.nim]: I can't get `{.strdefine.}` to work. When compiling with `-d:libname=/usr/lib/qrcodegen.so` the executable still uses the nimble path.

**Review by ThomasTJdev — CHANGES_REQUESTED** [review]

File: src/qr/qrcodegen.nim (hunk 3 above)
Comment (juancarlospaco) [reply src/qr/qrcodegen.nim]: Try with compiling again with `-f` ?, maybe add quotes `" "` to the path ?, weird it works on my machine. :thinking: 

https://nim-lang.github.io/Nim/manual.html#implementation-specific-pragmas-compileminustime-define-pragmas

File: src/qr.nim (hunk 2 above)
Comment (juancarlospaco) [reply src/qr.nim:81]: Yes, only for `bgColor` and `fgColor`.

File: src/qr.nim (hunk 1 above)
Comment (juancarlospaco) [reply src/qr.nim:115]: Yes, because `bgColor` and `fgColor` is inserted at compile-time, data and sizes is inserted at run-time,
at compile time `$$2` is escaped to `$2`, then `$2` is inserted at run-time, see https://play.nim-lang.org/#ix=2Hi8

File: src/qr/qrcodegen.nim (hunk 3 above)
Comment (ThomasTJdev) [reply src/qr/qrcodegen.nim]: Well, this is weird.. I tried with quotes and all.. I have looked into the cache directory. See this:

`@ma.nim.c`
```
/* section: NIM_merge_DATA */
STRING_LITERAL(TM__LSU9bViOd4immx1fl6MvEHQ_3, "/usr/lib/qrcodegen.so", 21);
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__LSU9bViOd4immx1fl6MvEHQ_2 = {((NimStringDesc*) &TM__LSU9bViOd4immx1fl6MvEHQ_3)}
;
```

`@msrc@sqr.nim.c`
```
/* section: NIM_merge_DATA */
STRING_LITERAL(TM__DW1kcEEkG4t559ckyjNU1Cw_4, "/home/user/git/nim_qr/src/qr/qrcodegen.so", 41);
STRING_LITERAL(TM__DW1kcEEkG4t559ckyjNU1Cw_5, "/home/user/git/nim_qr/src/qr/qrcodegen.so", 41);
static NIM_CONST tyArray__HU7qaqKu9czJLT84iCBJnsA TM__DW1kcEEkG4t559ckyjNU1Cw_10 = {((NI) 4),
((NI) 7)}
;
```

File: src/qr.nim (hunk 1 above)
Comment (ThomasTJdev) [reply src/qr.nim:115]: Thanks for explanation :)

File: src/qr/qrcodegen.nim (hunk 3 above)
Comment (juancarlospaco) [reply src/qr/qrcodegen.nim]: Use an empty folder as cache, like `-f --nimcache:.` or `-f --nimcache:/tmp` ?. :thinking:

Comment (ThomasTJdev) [reply src/qr/qrcodegen.nim]: Yeah - this is strange. I have also used the `--nimcache:` option, but with no luck.

Could you check your generated C-files?

`@m..@s..@s.nimble@spkgs@sqr-1.5.0@sqr.nim.c`
```
/* section: NIM_merge_DATA */
STRING_LITERAL(TM__DW1kcEEkG4t559ckyjNU1Cw_4, "/home/user/.nimble/pkgs/qr-1.5.0/qr/qrcodegen.so", 48);
STRING_LITERAL(TM__DW1kcEEkG4t559ckyjNU1Cw_5, "/home/user/.nimble/pkgs/qr-1.5.0/qr/qrcodegen.so", 48);
```

Comment (juancarlospaco) [reply src/qr/qrcodegen.nim]: It seems to be working on a simple example:

```console
$ cat a.nim 
const x* {.strdefine.} = "ABCDEF0123456"
echo x

$ nim c -r -d:danger -d:x:hola --nimcache:. a.nim 

$ cat @ma.nim.c | grep "ABCDEF0123456"

$ cat @ma.nim.c | grep "hola"
STRING_LITERAL(TM__R8RUzYq41iOx0I9bZH5Nyrw_3, "hola", 4);

$ 
```

Comment (juancarlospaco) [reply src/qr/qrcodegen.nim]: So it seems `{.strdefine.}` may not be reliable for this use case, the ones on stdlib do not use it,
maybe at compile-time those are evaluated at last moment,
do you want me to remove `{.strdefine.}` and go with the `try: ... except:` ?.

Comment (ThomasTJdev) [reply src/qr/qrcodegen.nim]: I can also make the small example work.. well, another solution it is. A `try: ... except:` would be fine with me.

1) I would prefer, that we start by looking in the default library folder, `/usr/lib/qrcodegen.so` (don't know with Windows and Mac), if it does not exists here, then we'll use the nimble. How does that sound for portability?

2) If we go with nr. 1, the `qr.nimble` should check in that folder before compiling it from C?

Comment (juancarlospaco) [reply src/qr/qrcodegen.nim]: @ThomasTJdev Something like this ?.
https://github.com/ThomasTJdev/nim_qr/pull/5/commits/2e54ca37f8cd01327061555d87b1ecb5f730150f

I dont know if this would work 100% of times, because needs sudo, Windows may block it, file permissions, antivirus, etc
but ultimately it prints clear instructions about copying the file manually. :thinking:

Comment (ThomasTJdev) [reply src/qr/qrcodegen.nim]: Yeah - I like that solution. It wont work out of the box due to the need of `sudo`, and we shouldn't run `nimble install` with `sudo`. The above works perfect for me cause I have the file in `/usr/lib`.

But. What if the user wants to ship the nimble-package with `qrcodegen.so`? Well, both the previous design and this PR does not give the user that possibility due to the `lib` being an absolute path. So we are blocking the *no-interaction* portability. To fix that it should be possible to use a relative path to the lib, or the lib should be included in the compiled file.

How does this sound to you:
* Merging this PR and updating the `README.md` with a clear description of it.
* Await another user with an innovative idea on a solution :)

Comment (juancarlospaco) [reply src/qr/qrcodegen.nim]: OK with the Merge. :+1: 

I think theres no silver bullet solution, shared libs are meant to work like that.
